// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./components/Container.vue')['default']
    GlobalCom: typeof import('./componentsGlobal/globalCom.vue')['default']
    LeftSidebar: typeof import('./components/container/leftSidebar.vue')['default']
    MouseSelect: typeof import('./components/mouseSelect.vue')['default']
    Pagination: typeof import('./components/pagination/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestGlobalCom: typeof import('./componentsGlobal/test/testGlobalCom.vue')['default']
    TopNavBar: typeof import('./components/container/topNavBar.vue')['default']
  }
}
