// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./components/Container.vue')['default']
    GlobalCom: typeof import('./componentsGlobal/globalCom.vue')['default']
    LeftSidebar: typeof import('./components/container/leftSidebar.vue')['default']
    MouseSelect: typeof import('./components/mouseSelect.vue')['default']
    Pagination: typeof import('./components/pagination/pagination.vue')['default']
    TestGlobalCom: typeof import('./componentsGlobal/test/testGlobalCom.vue')['default']
    TopNavBar: typeof import('./components/container/topNavBar.vue')['default']
  }
}

export { }
